name: RAG Evaluation

on:
  push:
    branches:
      - "main"

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt

      - name: Debug API file
        run: |
          echo "===== API FILE ====="
          cat api_service/app.py

      - name: Debug RAG file
        run: |
          echo "===== RAG FILE ====="
          cat rag_service/rag_app.py

      - name: Start RAG Service
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        run: |
          nohup env PINECONE_API_KEY=$PINECONE_API_KEY \
          HUGGINGFACEHUB_API_TOKEN=$HUGGINGFACEHUB_API_TOKEN \
          uvicorn rag_service.rag_app:app --port 8001 > rag.log 2>&1 &
          sleep 20
          cat rag.log   

      - name: Start API Service
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        run: |
          nohup env PINECONE_API_KEY=$PINECONE_API_KEY \
          HUGGINGFACEHUB_API_TOKEN=$HUGGINGFACEHUB_API_TOKEN \
          api_service.app:app --port 8000 > api.log 2>&1 &
          sleep 20
          cat api.log   

      - name: Test API
        run: |
          curl -v -X POST http://localhost:8000/ask \
          -H "Content-Type: application/json" \
          -d '{"question":"What are employee benefits?"}'


        